[project]
name = "comfyui-circle-detection"
description = "ComfyUI_Circle_Detection detects circles using a mathematical method called Houghs Transform for the detection."
version = "0.0.0.2"
license = "LICENSE"
dependencies = ["pillow", "torch"]

[project.urls]
Repository = "https://github.com/zentrocdot/ComfyUI_Circle_Detection"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "2ac5c8ff-686c-4f18-a4bc-2166c23cb1a5"
DisplayName = "ComfyUI_Circle_Detection"
Icon = ""
